// Liste statique des 75 fingerprints (nom + catégorie + icône) utilisée par la popup
// pour le menu de filtres. Doit rester synchronisée avec les fichiers fingerprints/*.js.
window.PokewebFingerprintsMeta = [
  // frontend-framework (14)
  { name: "React",         category: "frontend-framework", icon: "react"     },
  { name: "Vue",           category: "frontend-framework", icon: "vue"       },
  { name: "Svelte",        category: "frontend-framework", icon: "svelte"    },
  { name: "Angular",       category: "frontend-framework", icon: "angular"   },
  { name: "Solid",         category: "frontend-framework", icon: "solid"     },
  { name: "Preact",        category: "frontend-framework", icon: "preact"    },
  { name: "Alpine.js",     category: "frontend-framework", icon: "alpinejs"  },
  { name: "Lit",           category: "frontend-framework", icon: "lit"       },
  { name: "Ember.js",      category: "frontend-framework", icon: "ember"     },
  { name: "Qwik",          category: "frontend-framework", icon: "qwik"      },
  { name: "Backbone.js",   category: "frontend-framework", icon: "backbone"  },
  { name: "Mithril",       category: "frontend-framework", icon: "mithril"   },
  { name: "Aurelia",       category: "frontend-framework", icon: "aurelia"   },
  { name: "Riot.js",       category: "frontend-framework", icon: "riot"      },
  // meta-framework (6)
  { name: "Next.js",       category: "meta-framework",     icon: "nextjs"    },
  { name: "Nuxt",          category: "meta-framework",     icon: "nuxt"      },
  { name: "Remix",         category: "meta-framework",     icon: "remix"     },
  { name: "Astro",         category: "meta-framework",     icon: "astro"     },
  { name: "SvelteKit",     category: "meta-framework",     icon: "sveltekit" },
  { name: "Gatsby",        category: "meta-framework",     icon: "gatsby"    },
  // backend-framework (5)
  { name: "Express",       category: "backend-framework",  icon: "express"   },
  { name: "Laravel",       category: "backend-framework",  icon: "laravel"   },
  { name: "Django",        category: "backend-framework",  icon: "django"    },
  { name: "Ruby on Rails", category: "backend-framework",  icon: "rails"     },
  { name: "ASP.NET",       category: "backend-framework",  icon: "aspnet"    },
  // cms (12)
  { name: "WordPress",     category: "cms",                icon: "wordpress"  },
  { name: "Shopify",       category: "cms",                icon: "shopify"    },
  { name: "Webflow",       category: "cms",                icon: "webflow"    },
  { name: "Ghost",         category: "cms",                icon: "ghost"      },
  { name: "Wix",           category: "cms",                icon: "wix"        },
  { name: "Squarespace",   category: "cms",                icon: "squarespace"},
  { name: "Drupal",        category: "cms",                icon: "drupal"     },
  { name: "Joomla",        category: "cms",                icon: "joomla"     },
  { name: "Magento",       category: "cms",                icon: "magento"    },
  { name: "WooCommerce",   category: "cms",                icon: "woocommerce"},
  { name: "PrestaShop",    category: "cms",                icon: "prestashop" },
  { name: "OpenCart",      category: "cms",                icon: "opencart"   },
  // css-framework (10)
  { name: "Tailwind CSS",       category: "css-framework", icon: "tailwind"        },
  { name: "Bootstrap",          category: "css-framework", icon: "bootstrap"       },
  { name: "Bulma",              category: "css-framework", icon: "bulma"           },
  { name: "Chakra UI",          category: "css-framework", icon: "chakra"          },
  { name: "Material UI",        category: "css-framework", icon: "mui"             },
  { name: "Foundation",         category: "css-framework", icon: "foundation"      },
  { name: "Ant Design",         category: "css-framework", icon: "antdesign"       },
  { name: "Framer Motion",      category: "css-framework", icon: "framermotion"    },
  { name: "Styled Components",  category: "css-framework", icon: "styledcomponents"},
  { name: "Emotion",            category: "css-framework", icon: "emotion"         },
  // js-library (7)
  { name: "jQuery",      category: "js-library", icon: "jquery"  },
  { name: "Three.js",    category: "js-library", icon: "three"   },
  { name: "D3.js",       category: "js-library", icon: "d3"      },
  { name: "Chart.js",    category: "js-library", icon: "chartjs" },
  { name: "GSAP",        category: "js-library", icon: "gsap"    },
  { name: "Moment.js",   category: "js-library", icon: "moment"  },
  { name: "Day.js",      category: "js-library", icon: "dayjs"   },
  // web-server (6)
  { name: "Nginx",         category: "web-server", icon: "nginx"     },
  { name: "Apache",        category: "web-server", icon: "apache"    },
  { name: "Caddy",         category: "web-server", icon: "caddy"     },
  { name: "LiteSpeed",     category: "web-server", icon: "litespeed" },
  { name: "Microsoft IIS", category: "web-server", icon: "iis"       },
  { name: "Varnish",       category: "web-server", icon: "varnish"   },
  // hosting (6)
  { name: "Vercel",        category: "hosting", icon: "vercel"     },
  { name: "Netlify",       category: "hosting", icon: "netlify"    },
  { name: "Cloudflare",    category: "hosting", icon: "cloudflare" },
  { name: "AWS CloudFront",category: "hosting", icon: "cloudfront" },
  { name: "GitHub Pages",  category: "hosting", icon: "github"     },
  { name: "Fastly",        category: "hosting", icon: "fastly"     },
  // analytics (9)
  { name: "Google Analytics", category: "analytics", icon: "googleanalytics" },
  { name: "Plausible",        category: "analytics", icon: "plausible"       },
  { name: "Fathom",           category: "analytics", icon: "fathom"          },
  { name: "PostHog",          category: "analytics", icon: "posthog"         },
  { name: "Mixpanel",         category: "analytics", icon: "mixpanel"        },
  { name: "Hotjar",           category: "analytics", icon: "hotjar"          },
  { name: "Segment",          category: "analytics", icon: "segment"         },
  { name: "Sentry",           category: "analytics", icon: "sentry"          },
  { name: "Firebase",         category: "analytics", icon: "firebase"        },
];
