window.PokewebIconsMap = {
  // frontend frameworks
  react:              "⚛️",
  vue:                "🟩",
  svelte:             "🔥",
  angular:            "🅰️",
  solid:              "🔷",
  preact:             "⚡",
  alpinejs:           "⛰️",
  lit:                "🔥",
  ember:              "🐹",
  qwik:               "⚡",
  backbone:           "🦴",
  mithril:            "⚒️",
  aurelia:            "💎",
  riot:               "🎭",
  // meta-frameworks
  nextjs:             "▲",
  nuxt:               "🟢",
  remix:              "💿",
  astro:              "🚀",
  sveltekit:          "🔥",
  gatsby:             "🟣",
  // css frameworks
  tailwind:           "🌬️",
  bootstrap:          "🅱️",
  bulma:              "💧",
  chakra:             "⚡",
  mui:                "Ⓜ️",
  foundation:         "🏛️",
  antdesign:          "🐜",
  framermotion:       "🎞️",
  styledcomponents:   "💅",
  emotion:            "💖",
  // cms
  wordpress:          "📝",
  shopify:            "🛍️",
  webflow:            "🌊",
  ghost:              "👻",
  wix:                "🎨",
  squarespace:        "⬛",
  drupal:             "💧",
  joomla:             "🅹",
  magento:            "🟠",
  woocommerce:        "🛒",
  prestashop:         "🛍️",
  opencart:           "🛒",
  // backend frameworks
  express:            "🚂",
  laravel:            "🔴",
  django:             "🟢",
  rails:              "🛤️",
  aspnet:             "🔷",
  // js libraries
  jquery:             "💲",
  three:              "🎲",
  d3:                 "📊",
  chartjs:            "📈",
  gsap:               "🎬",
  moment:             "🕐",
  dayjs:              "📅",
  // web servers
  nginx:              "🟢",
  apache:             "🪶",
  caddy:              "🚀",
  litespeed:          "💨",
  iis:                "🪟",
  varnish:            "🎨",
  // hosting / cdn
  vercel:             "▲",
  netlify:            "🟢",
  cloudflare:         "🟠",
  cloudfront:         "☁️",
  github:             "🐙",  // icon utilisé par GitHub Pages dans hosting.js
  githubpages:        "🐙",
  fastly:             "💨",
  // analytics
  googleanalytics:    "📊",
  plausible:          "📈",
  fathom:             "🐟",
  posthog:            "🦔",
  mixpanel:           "🎛️",
  hotjar:             "🔥",
  segment:            "📐",
  sentry:             "👁️",
  firebase:           "🔥",
};
